from typing import Protocol, Any, AsyncContextManager, Literal


class LoggerLike(Protocol):
    def debug(self, msg: str, *args, **kwargs) -> None: ...
    def info(self, msg: str, *args, **kwargs) -> None: ...
    def warning(self, msg: str, *args, **kwargs) -> None: ...
    def error(self, msg: str, *args, **kwargs) -> None: ...
    def exception(self, msg: str, *args, **kwargs) -> None: ...
    def critical(self, msg: str, *args, **kwargs) -> None: ...


class WebSocketClient(Protocol):
    async def send(self, data: Any) -> None: ...
    async def recv(self) -> Any: ...

class WebsocketsModule(Protocol):
    async def connect(
        self,
        uri: str,
        **kwargs: Any,
    ) -> AsyncContextManager[WebSocketClient]:
        ...


UserPrivilege = Literal["user", "admin"]